'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { GitBranch, Construction, Download, Copy } from 'lucide-react'

const TEMPLATES = [
  'Node.js', 'Python', 'Java', 'Go', 'Rust', 'Ruby', 'PHP', 'Swift', 'Kotlin',
  'React', 'Next.js', 'Vue', 'Angular', 'Django', 'Laravel', 'Rails',
  'VS Code', 'JetBrains', 'Xcode', 'macOS', 'Windows', 'Linux',
  'Docker', 'Terraform', 'Ansible',
]

const PREVIEW = `# Generated by MicroApps .gitignore Generator

# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.env
.env.local
.env.*.local

# Next.js
.next/
out/
build/

# VS Code
.vscode/*
!.vscode/extensions.json

# macOS
.DS_Store
.AppleDouble
.LSOverride
Thumbs.db`

export default function GitignoreGenerator() {
  const [selected, setSelected] = useState<Set<string>>(new Set(['Node.js', 'Next.js', 'VS Code', 'macOS']))

  function toggle(t: string) {
    setSelected(prev => {
      const next = new Set(prev)
      next.has(t) ? next.delete(t) : next.add(t)
      return next
    })
  }

  return (
    <div className="max-w-3xl mx-auto space-y-5">
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Input placeholder="Search templates…" className="h-9 max-w-xs" />
          <span className="text-xs text-muted-foreground">{selected.size} selected</span>
        </div>
        <div className="flex flex-wrap gap-2">
          {TEMPLATES.map(t => (
            <button key={t} onClick={() => toggle(t)}
              className={`text-xs px-3 py-1.5 rounded-lg border transition-colors ${selected.has(t) ? 'bg-primary text-primary-foreground border-primary' : 'border-border hover:bg-muted/50 text-muted-foreground'}`}>
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="rounded-xl border overflow-hidden">
        <div className="px-4 py-2.5 border-b bg-muted/30 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <GitBranch className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-xs font-medium">.gitignore preview</span>
          </div>
          <div className="flex gap-1.5">
            <Button size="sm" variant="ghost" className="h-6 px-2 text-xs gap-1 opacity-60" disabled>
              <Copy className="h-3 w-3" /> Copy
            </Button>
            <Button size="sm" variant="ghost" className="h-6 px-2 text-xs gap-1 opacity-60" disabled>
              <Download className="h-3 w-3" /> Download
            </Button>
          </div>
        </div>
        <pre className="p-4 text-xs font-mono text-muted-foreground overflow-auto max-h-72">{PREVIEW}</pre>
      </div>

      <div className="flex items-center gap-3">
        <Button disabled className="gap-2 opacity-60">
          <GitBranch className="h-4 w-4" /> Generate .gitignore
        </Button>
        <Badge variant="outline" className="gap-1.5 text-amber-600 border-amber-400/40">
          <Construction className="h-3.5 w-3.5" /> Coming soon
        </Badge>
      </div>
    </div>
  )
}
