'use client'

import { useState } from 'react'
import { PdfDropzone } from '@/components/pdf-dropzone'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { Bookmark, Construction } from 'lucide-react'

export default function PdfBookmarkGenerator() {
  const [file, setFile] = useState<File | null>(null)

  return (
    <div className="space-y-5 max-w-2xl mx-auto">
      <PdfDropzone file={file} onFile={setFile} label="Drop a PDF to generate bookmarks" />

      <div className="rounded-xl border p-5 space-y-4">
        <h3 className="text-sm font-medium">Bookmark Generation</h3>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label className="text-xs mb-1.5 block">Detection method</Label>
            <Select defaultValue="headings">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="headings">Font size headings</SelectItem>
                <SelectItem value="toc">From table of contents</SelectItem>
                <SelectItem value="manual">Manual entry</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label className="text-xs mb-1.5 block">Depth levels</Label>
            <Select defaultValue="3">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1 level (H1 only)</SelectItem>
                <SelectItem value="2">2 levels (H1, H2)</SelectItem>
                <SelectItem value="3">3 levels (H1–H3)</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div>
          <Label className="text-xs mb-1.5 block">Minimum heading font size (pt)</Label>
          <Input type="number" defaultValue="14" className="h-9 max-w-[120px]" />
        </div>
        <div className="bg-muted/30 rounded-lg p-3 text-xs text-muted-foreground">
          Bookmarks (outline/TOC) are generated by detecting heading styles in the PDF. Works best with text-based PDFs.
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Button disabled className="gap-2 opacity-60">
          <Bookmark className="h-4 w-4" /> Generate Bookmarks
        </Button>
        <Badge variant="outline" className="gap-1.5 text-amber-600 border-amber-400/40">
          <Construction className="h-3.5 w-3.5" /> Coming soon
        </Badge>
      </div>
    </div>
  )
}
