'use client'

import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Bot, Construction, Copy, Plus } from 'lucide-react'

const PREVIEW = `# robots.txt — generated by MicroApps
# https://example.com/robots.txt

User-agent: *
Disallow: /admin/
Disallow: /api/
Disallow: /private/
Disallow: /*.json$
Allow: /api/public/

User-agent: Googlebot
Allow: /

User-agent: GPTBot
Disallow: /

Sitemap: https://example.com/sitemap.xml
Sitemap: https://example.com/sitemap-blog.xml`

const PRESETS = ['Allow all bots', 'Block all bots', 'SEO-friendly', 'Block AI crawlers', 'E-commerce', 'Custom']

export default function RobotsTxtGenerator() {
  return (
    <div className="max-w-2xl mx-auto space-y-5">
      <div className="rounded-xl border p-3 space-y-2">
        <p className="text-xs text-muted-foreground font-medium">Quick presets</p>
        <div className="flex flex-wrap gap-1.5">
          {PRESETS.map(p => (
            <button key={p} disabled
              className="text-xs px-2.5 py-1 rounded-md border text-muted-foreground opacity-60 cursor-not-allowed">{p}</button>
          ))}
        </div>
      </div>

      <div className="rounded-xl border p-4 space-y-3">
        <p className="text-xs font-medium">Rules</p>
        <div className="space-y-2">
          {[
            { agent: '*',         type: 'Disallow', path: '/admin/' },
            { agent: '*',         type: 'Disallow', path: '/api/' },
            { agent: '*',         type: 'Allow',    path: '/api/public/' },
            { agent: 'GPTBot',    type: 'Disallow', path: '/' },
          ].map((r, i) => (
            <div key={i} className="grid grid-cols-7 gap-2 items-center text-xs opacity-70">
              <Input defaultValue={r.agent} disabled className="col-span-2 h-7 font-mono text-xs" />
              <Badge variant="outline" className={`col-span-1 justify-center text-[10px] ${r.type === 'Allow' ? 'text-green-600 border-green-400/40' : 'text-red-600 border-red-400/40'}`}>{r.type}</Badge>
              <Input defaultValue={r.path} disabled className="col-span-3 h-7 font-mono text-xs" />
              <button disabled className="opacity-40 cursor-not-allowed justify-self-center">✕</button>
            </div>
          ))}
        </div>
        <Button size="sm" variant="outline" disabled className="h-7 gap-1 text-xs opacity-60">
          <Plus className="h-3.5 w-3.5" /> Add Rule
        </Button>
        <div>
          <Label className="text-xs mb-1 block">Sitemap URL</Label>
          <Input defaultValue="https://example.com/sitemap.xml" disabled className="h-8 text-xs font-mono opacity-60" />
        </div>
      </div>

      <div className="rounded-xl border overflow-hidden opacity-70">
        <div className="px-4 py-2.5 border-b bg-muted/30 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Bot className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-xs font-medium">robots.txt output</span>
          </div>
          <button disabled className="opacity-40 cursor-not-allowed"><Copy className="h-3.5 w-3.5 text-muted-foreground" /></button>
        </div>
        <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto whitespace-pre">{PREVIEW}</pre>
        <div className="px-4 py-2 bg-muted/20 text-[10px] text-muted-foreground/60 text-center">(Preview only — functionality coming soon)</div>
      </div>

      <div className="flex items-center gap-3">
        <Button disabled className="gap-2 opacity-60"><Bot className="h-4 w-4" /> Generate</Button>
        <Badge variant="outline" className="gap-1.5 text-amber-600 border-amber-400/40">
          <Construction className="h-3.5 w-3.5" /> Coming soon
        </Badge>
      </div>
    </div>
  )
}
